name: Backend CI

on:
  push:
    paths:
      - 'Backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    paths:
      - 'Backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Backend/EmployeeManagementSystem.sln

      - name: Build solution
        run: dotnet build Backend/EmployeeManagementSystem.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test Backend/EmployeeManagementSystem.Tests/EmployeeManagementSystem.Tests.csproj --no-build --configuration Release --verbosity normal
