name: Frontend CD (Angular Deploy to GitHub Pages)

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build Angular production
        working-directory: frontend
        run: ng build --configuration production --base-href=/employee-management-system/

      - name: Deploy to GitHub Pages
        working-directory: frontend
        uses: angular-schule/angular-cli-ghpages@v2
        with:
          build-target: employee-management-client:build:production
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_branch: gh-pages
          base_href: /employee-management-system/
