name: Test Secrets

on: [workflow_dispatch]

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Show Secret Value
        run: echo "SECRET_VALUE=${{ secrets.YOUR_SECRET_NAME }}"
